CC=g++
CFLAG=-std=c++17 -Wall
INC=-I/usr/include/cppconn
LIB=-L/usr/lib -lmysqlcppconn -lstdc++fs

gen:
	${CC} ${CFLAG} ${INC} -o formated_examples_with_database ./formated_examples_with_database.cpp -L/usr/lib ${LIB}
